/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoActividadesRouteImport } from './routes/demo.actividades'
import { Route as DemoAdaptativoRouteImport } from './routes/demo.adaptativo'
import { Route as DemoAlertasRouteImport } from './routes/demo.alertas'
import { Route as DemoAlumnadoRouteImport } from './routes/demo.alumnado'
import { Route as DemoConfigRouteImport } from './routes/demo.config'
import { Route as DemoGemeloRouteImport } from './routes/demo.gemelo'
import { Route as DemoInformesRouteImport } from './routes/demo.informes'
import { Route as DemoAlumnoIdRouteImport } from './routes/demo.alumno.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoActividadesRoute = DemoActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAdaptativoRoute = DemoAdaptativoRouteImport.update({
  id: '/adaptativo',
  path: '/adaptativo',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAlertasRoute = DemoAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAlumnadoRoute = DemoAlumnadoRouteImport.update({
  id: '/alumnado',
  path: '/alumnado',
  getParentRoute: () => DemoRoute,
} as any)
const DemoConfigRoute = DemoConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DemoRoute,
} as any)
const DemoGemeloRoute = DemoGemeloRouteImport.update({
  id: '/gemelo',
  path: '/gemelo',
  getParentRoute: () => DemoRoute,
} as any)
const DemoInformesRoute = DemoInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAlumnoIdRoute = DemoAlumnoIdRouteImport.update({
  id: '/alumno/$id',
  path: '/alumno/$id',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/actividades': typeof DemoActividadesRoute
  '/demo/adaptativo': typeof DemoAdaptativoRoute
  '/demo/alertas': typeof DemoAlertasRoute
  '/demo/alumnado': typeof DemoAlumnadoRoute
  '/demo/config': typeof DemoConfigRoute
  '/demo/gemelo': typeof DemoGemeloRoute
  '/demo/informes': typeof DemoInformesRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/alumno/$id': typeof DemoAlumnoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/actividades': typeof DemoActividadesRoute
  '/demo/adaptativo': typeof DemoAdaptativoRoute
  '/demo/alertas': typeof DemoAlertasRoute
  '/demo/alumnado': typeof DemoAlumnadoRoute
  '/demo/config': typeof DemoConfigRoute
  '/demo/gemelo': typeof DemoGemeloRoute
  '/demo/informes': typeof DemoInformesRoute
  '/demo': typeof DemoIndexRoute
  '/demo/alumno/$id': typeof DemoAlumnoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/actividades': typeof DemoActividadesRoute
  '/demo/adaptativo': typeof DemoAdaptativoRoute
  '/demo/alertas': typeof DemoAlertasRoute
  '/demo/alumnado': typeof DemoAlumnadoRoute
  '/demo/config': typeof DemoConfigRoute
  '/demo/gemelo': typeof DemoGemeloRoute
  '/demo/informes': typeof DemoInformesRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/alumno/$id': typeof DemoAlumnoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/demo/actividades'
    | '/demo/adaptativo'
    | '/demo/alertas'
    | '/demo/alumnado'
    | '/demo/config'
    | '/demo/gemelo'
    | '/demo/informes'
    | '/demo/'
    | '/demo/alumno/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/actividades'
    | '/demo/adaptativo'
    | '/demo/alertas'
    | '/demo/alumnado'
    | '/demo/config'
    | '/demo/gemelo'
    | '/demo/informes'
    | '/demo'
    | '/demo/alumno/$id'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/demo/actividades'
    | '/demo/adaptativo'
    | '/demo/alertas'
    | '/demo/alumnado'
    | '/demo/config'
    | '/demo/gemelo'
    | '/demo/informes'
    | '/demo/'
    | '/demo/alumno/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/actividades': {
      id: '/demo/actividades'
      path: '/actividades'
      fullPath: '/demo/actividades'
      preLoaderRoute: typeof DemoActividadesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/adaptativo': {
      id: '/demo/adaptativo'
      path: '/adaptativo'
      fullPath: '/demo/adaptativo'
      preLoaderRoute: typeof DemoAdaptativoRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/alertas': {
      id: '/demo/alertas'
      path: '/alertas'
      fullPath: '/demo/alertas'
      preLoaderRoute: typeof DemoAlertasRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/alumnado': {
      id: '/demo/alumnado'
      path: '/alumnado'
      fullPath: '/demo/alumnado'
      preLoaderRoute: typeof DemoAlumnadoRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/config': {
      id: '/demo/config'
      path: '/config'
      fullPath: '/demo/config'
      preLoaderRoute: typeof DemoConfigRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/gemelo': {
      id: '/demo/gemelo'
      path: '/gemelo'
      fullPath: '/demo/gemelo'
      preLoaderRoute: typeof DemoGemeloRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/informes': {
      id: '/demo/informes'
      path: '/informes'
      fullPath: '/demo/informes'
      preLoaderRoute: typeof DemoInformesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/alumno/$id': {
      id: '/demo/alumno/$id'
      path: '/alumno/$id'
      fullPath: '/demo/alumno/$id'
      preLoaderRoute: typeof DemoAlumnoIdRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoActividadesRoute: typeof DemoActividadesRoute
  DemoAdaptativoRoute: typeof DemoAdaptativoRoute
  DemoAlertasRoute: typeof DemoAlertasRoute
  DemoAlumnadoRoute: typeof DemoAlumnadoRoute
  DemoConfigRoute: typeof DemoConfigRoute
  DemoGemeloRoute: typeof DemoGemeloRoute
  DemoInformesRoute: typeof DemoInformesRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoAlumnoIdRoute: typeof DemoAlumnoIdRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoActividadesRoute: DemoActividadesRoute,
  DemoAdaptativoRoute: DemoAdaptativoRoute,
  DemoAlertasRoute: DemoAlertasRoute,
  DemoAlumnadoRoute: DemoAlumnadoRoute,
  DemoConfigRoute: DemoConfigRoute,
  DemoGemeloRoute: DemoGemeloRoute,
  DemoInformesRoute: DemoInformesRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoAlumnoIdRoute: DemoAlumnoIdRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
